hydra:
  run:
    dir: .
  output_subdir: null

folder: ???
split: gtest

mean: false
number_of_samples: 1
fact: 1

# only needed for amass
jointstype: mmm

# if jointstype == vertices or mmm
# can specify the gender
# neutral / male / female
gender: neutral

logger_level: INFO

defaults:
  - /path@path
  - /transforms/rots2joints/smplh@rots2joints
  - override hydra/job_logging: rich # console
  - override hydra/hydra_logging: rich # console
  - _self_

machine:
  smpl_batch_size: 256
