name: SMPLVelP
_target_: temos.transforms.rots2rfeats.SMPLVelP

pose_rep: rot6d
path: ${path.deps}/transforms/rots2rfeats/smplvelp/${.pose_rep}/${data.dataname}

canonicalize: true
normalization: true
